export const complaintList: any =
    {
        "content": [{
            "id": "rbumroljknnxwuomadtmmiqp",
            "rdId": null,
            "typeCode": "1",
            "complaintTypeCode": "1",
            "name": "胡紫",
            "complaintContext": "erwer",
            "anonymous": 0,
            "complaintTitle": null,
            "complaintTarget": null,
            "contactTel": "12333***xx",
            "email": null,
            "address": null,
            "roomId": "NH-1-1-102",
            "complaintTime": "2020-10-20 16:29:45",
            "disposeTypeCode": "0",
            "evaluateCode": null,
            "createPerson": "566045cbdd621dff8c0f6bc1",
            "createTime": "2020-10-20 16:29:45",
            "updateTime": "2020-10-20 16:29:45",
            "deleted": 0,
            "complaintAttachments": [],
            "complaintFeedback": null,
            "roomName": "NH-1-1-102"
        },
            {
                "id": "flklrygdypzntdkstkckmamv",
                "rdId": null,
                "typeCode": "1",
                "complaintTypeCode": "1",
                "name": "莉莉",
                "complaintContext": "this drama",
                "anonymous": 0,
                "complaintTitle": null,
                "complaintTarget": null,
                "contactTel": "1569159159",
                "email": null,
                "address": null,
                "roomId": "nlncfxkdzhnjzufudcyrqkcc",
                "complaintTime": "2020-09-30 14:20:56",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "createTime": "2020-09-30 14:20:56",
                "updateTime": "2020-09-30 14:20:56",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": "zz3301201"
            },
            {
                "id": "hjamnoxtnlprhttznhhyyrqe",
                "rdId": null,
                "typeCode": "1",
                "complaintTypeCode": "1",
                "name": "张长",
                "complaintContext": "3333",
                "anonymous": 0,
                "complaintTitle": null,
                "complaintTarget": null,
                "contactTel": "12313123",
                "email": null,
                "address": null,
                "roomId": "fnmawoweglcdaoerzjwcpajs",
                "complaintTime": "2020-09-30 13:09:21",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "createTime": "2020-09-30 13:09:21",
                "updateTime": "2020-09-30 13:09:21",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": "zz3301102"
            },
            {
                "id": "dvgvmwvhxfwawitdwseykdvi",
                "rdId": "GLC0000015",
                "typeCode": "1",
                "complaintTypeCode": "1",
                "name": "张艺兴",
                "complaintContext": "阿斯蒂芬",
                "anonymous": 0,
                "complaintTitle": "发送到发",
                "complaintTarget": "阿斯蒂芬",
                "contactTel": "17376561010",
                "email": "1547362950@qq.com",
                "address": " 阿斯蒂芬",
                "roomId": null,
                "complaintTime": "2020-09-27 14:42:22",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "createTime": "2020-09-27 14:42:22",
                "updateTime": "2020-09-27 14:42:22",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": null
            },
            {
                "id": "ibdfjetuispwcaohobsvaurv",
                "rdId": "GLC0000015",
                "typeCode": "1",
                "complaintTypeCode": "1",
                "name": "张三",
                "complaintContext": "房屋质量差,地面瓷砖破裂8888",
                "anonymous": 0,
                "complaintTitle": "房屋质量差",
                "complaintTarget": "物业公司",
                "contactTel": "18377831823",
                "email": "zhangs@sucsoft.com",
                "address": "西湖科技园7楼",
                "roomId": null,
                "complaintTime": "2020-09-27 14:39:08",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "createTime": "2020-09-27 14:39:08",
                "updateTime": "2020-09-27 14:39:08",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": null
            },
            {
                "id": "bvnvmyhjsucobvmgifqvedta",
                "rdId": "GLC0000015",
                "typeCode": "1",
                "complaintTypeCode": "1",
                "name": "张艺兴",
                "complaintContext": "阿是的发送到发送到发是的发生的发是的发送到发送到发送",
                "anonymous": 0,
                "complaintTitle": "测试投诉",
                "complaintTarget": "物业公司",
                "contactTel": "17376561010",
                "email": "1547362950@qq.com",
                "address": "",
                "roomId": null,
                "complaintTime": "2020-09-26 21:13:05",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "createTime": "2020-09-26 21:13:05",
                "updateTime": "2020-09-26 21:13:05",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": null
            },
            {
                "id": "rxxweuwaohzxqbsdeirthrax",
                "rdId": "GLC0000015",
                "typeCode": "1",
                "complaintTypeCode": "1",
                "name": "张三",
                "complaintContext": "房屋质量差,地面瓷砖破裂7777",
                "anonymous": 0,
                "complaintTitle": "房屋质量差",
                "complaintTarget": "物业公司",
                "contactTel": "18377831823",
                "email": "zhangs@sucsoft.com",
                "address": "西湖科技园7楼",
                "roomId": null,
                "complaintTime": "2020-09-26 21:11:47",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "createTime": "2020-09-26 21:11:47",
                "updateTime": "2020-09-26 21:11:47",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": null
            },
            {
                "id": "idphyjyzymaojsnwjggrlxle",
                "rdId": "GLC0000015",
                "typeCode": "1",
                "complaintTypeCode": "1",
                "name": "张三",
                "complaintContext": "房屋质量差,地面瓷砖破裂6666",
                "anonymous": 0,
                "complaintTitle": "房屋质量差",
                "complaintTarget": "物业公司",
                "contactTel": "18377831823",
                "email": "zhangs@sucsoft.com",
                "address": "西湖科技园7楼",
                "roomId": null,
                "complaintTime": "2020-09-26 21:03:52",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "createTime": "2020-09-26 21:03:52",
                "updateTime": "2020-09-26 21:03:52",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": null
            },
            {
                "id": "pocadkqyiijnurtbwykqtzjo",
                "rdId": "GLC0000015",
                "typeCode": "1",
                "complaintTypeCode": "1",
                "name": "张艺兴",
                "complaintContext": "墙体有空鼓，渗水",
                "anonymous": 0,
                "complaintTitle": "测试投诉",
                "complaintTarget": "工程部",
                "contactTel": "17376561010",
                "email": "1547362950@qq.com",
                "address": "",
                "roomId": null,
                "complaintTime": "2020-09-25 17:17:49",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "createTime": "2020-09-25 17:17:49",
                "updateTime": "2020-09-25 17:17:49",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": null
            },
            {
                "id": "lezpjiwpqkdqmqyoajvadddl",
                "rdId": "GLC0000015",
                "typeCode": "1",
                "complaintTypeCode": "1",
                "name": "张三",
                "complaintContext": "房屋质量差,地面瓷砖破裂",
                "anonymous": 0,
                "complaintTitle": "房屋质量差",
                "complaintTarget": "物业公司",
                "contactTel": "18377831823",
                "email": "zhangs@sucsoft.com",
                "address": "西湖科技园7楼",
                "roomId": null,
                "complaintTime": "2020-07-22 15:54:47",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "createTime": "2020-07-22 15:54:32",
                "updateTime": "2020-07-22 15:54:32",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": null
            },
            {
                "id": "5",
                "rdId": "GLC0000015",
                "typeCode": "1",
                "complaintTypeCode": null,
                "name": "",
                "complaintContext": "半夜12点,楼上经常听到有赌博的声音",
                "anonymous": 1,
                "complaintTitle": "违法乱纪",
                "complaintTarget": "社区",
                "contactTel": "15267002015",
                "email": "1547362951@qq.com",
                "address": "瓜山北苑1-2-201",
                "roomId": null,
                "complaintTime": "2020-05-05 17:08:25",
                "disposeTypeCode": "0",
                "evaluateCode": "",
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "createTime": "2020-05-05 18:01:22",
                "updateTime": "2020-05-05 18:01:22",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": null
            },
            {
                "id": "3",
                "rdId": "GLC0000015",
                "typeCode": "1",
                "complaintTypeCode": null,
                "name": "",
                "complaintContext": "南门口绿化带被破坏后,未修复",
                "anonymous": 1,
                "complaintTitle": "绿化带破损",
                "complaintTarget": "物业",
                "contactTel": "15267002015",
                "email": "1547362951@qq.com",
                "address": "瓜山东苑1-4-201",
                "roomId": null,
                "complaintTime": "2020-05-05 17:08:18",
                "disposeTypeCode": "0",
                "evaluateCode": "",
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "createTime": "2020-05-05 18:01:22",
                "updateTime": "2020-05-05 18:01:22",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": null
            }
        ],
        "pageable": {
            "sort": {
                "sorted": false,
                "unsorted": true,
                "empty": true
            },
            "pageNumber": 0,
            "pageSize": 12,
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "totalPages": 2,
        "totalElements": 15,
        "last": false,
        "sort": {
            "sorted": false,
            "unsorted": true,
            "empty": true
        },
        "numberOfElements": 12,
        "first": true,
        "size": 12,
        "number": 0,
        "empty": false
    }

export const adviceList: any =
    {
        "content": [
            {
            "id": "utyzydhwwjhbjouvfeewzlho",
            "rdId": null,
            "typeCode": "0",
            "complaintTypeCode": "1",
            "name": "zzz",
            "complaintContext": "33123123",
            "anonymous": 0,
            "complaintTitle": null,
            "complaintTarget": null,
            "contactTel": "2131321313",
            "email": null,
            "address": null,
            "roomId": "RYY－1-1-101",
            "complaintTime": "2020-11-11 09:59:50",
            "disposeTypeCode": "0",
            "evaluateCode": null,
            "createPerson": "566045cbdd621dff8c0f6bc1",
            "createTime": "2020-11-11 09:59:50",
            "updateTime": "2020-11-11 09:59:50",
            "deleted": 0,
            "complaintAttachments": [],
            "complaintFeedback": null,
            "roomName": "RYY－1-1-101"
        },
            {
                "id": "twqkawyjyyribqetjkraqsje",
                "rdId": null,
                "typeCode": "0",
                "complaintTypeCode": "1",
                "name": "王林",
                "complaintContext": "69--696ee",
                "anonymous": 0,
                "complaintTitle": null,
                "complaintTarget": null,
                "contactTel": "145145145",
                "email": null,
                "address": null,
                "roomId": "nlncfxkdzhnjzufudcyrqkcc",
                "complaintTime": "2020-09-30 14:22:45",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "createTime": "2020-09-30 14:22:45",
                "updateTime": "2020-09-30 14:22:45",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": "zz3301201"
            },
            {
                "id": "elxppyeikvhvkymzsmumgqrj",
                "rdId": null,
                "typeCode": "0",
                "complaintTypeCode": "2",
                "name": "我我我",
                "complaintContext": "二等分",
                "anonymous": 0,
                "complaintTitle": null,
                "complaintTarget": null,
                "contactTel": "333123",
                "email": null,
                "address": null,
                "roomId": "nlncfxkdzhnjzufudcyrqkcc",
                "complaintTime": "2020-09-30 14:19:38",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "createTime": "2020-09-30 14:19:38",
                "updateTime": "2020-09-30 14:19:38",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": "zz3301201"
            },
            {
                "id": "mytpdwqifcqohjvrdctdomuw",
                "rdId": "GLC0000015",
                "typeCode": "0",
                "complaintTypeCode": "2",
                "name": "赵阳",
                "complaintContext": "调亮路灯",
                "anonymous": 1,
                "complaintTitle": "测试建议",
                "complaintTarget": "物业公司",
                "contactTel": "15388655698",
                "email": "",
                "address": "",
                "roomId": "NH-EN-02",
                "complaintTime": "2020-09-25 17:55:09",
                "disposeTypeCode": "0",
                "evaluateCode": null,
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "createTime": "2020-09-25 17:55:09",
                "updateTime": "2020-09-25 17:55:09",
                "deleted": 0,
                "complaintAttachments": [],
                "complaintFeedback": null,
                "roomName": "NH-EN-02",
            }
        ],
        "pageable": {
            "sort": {
                "sorted": false,
                "unsorted": true,
                "empty": true
            },
            "pageNumber": 0,
            "pageSize": 12,
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "totalPages": 1,
        "totalElements": 4,
        "last": true,
        "sort": {
            "sorted": false,
            "unsorted": true,
            "empty": true
        },
        "numberOfElements": 4,
        "first": true,
        "size": 12,
        "number": 0,
        "empty": false
    }


export const complaintDetail: any =
    {
        "id": "rbumroljknnxwuomadtmmiqp",
        "rdId": null,
        "typeCode": "1",
        "complaintTypeCode": "1",
        "name": "胡紫",
        "complaintContext": "erwer",
        "anonymous": 0,
        "complaintTitle": null,
        "complaintTarget": null,
        "contactTel": "12333***xx",
        "email": null,
        "address": null,
        "roomId": "NH-1-1-102",
        "complaintTime": "2020-10-20 16:29:45",
        "disposeTypeCode": "0",
        "evaluateCode": null,
        "createPerson": "566045cbdd621dff8c0f6bc1",
        "createTime": "2020-10-20 16:29:45",
        "updateTime": "2020-10-20 16:29:45",
        "deleted": 0,
        "complaintAttachments": [],
        "complaintFeedback": {
            "id": "edyolcfeayogugkwwelushaz",
            "complaintId": "rbumroljknnxwuomadtmmiqp",
            "disposeResult": "嗯嗯嗯",
            "feedbackTime": "2020-10-20 16:29:58",
            "disposePerson": "566045cbdd621dff8c0f6bc1",
            "disposePersonName": "超级管理员"
        },
        "roomName": "NH-1-1-102"
    }

export const adviceDetail: any =
    {
        "id": "mytpdwqifcqohjvrdctdomuw",
        "rdId": "GLC0000015",
        "typeCode": "0",
        "complaintTypeCode": "2",
        "name": "赵阳",
        "complaintContext": "调亮路灯",
        "anonymous": 1,
        "complaintTitle": "测试建议",
        "complaintTarget": "物业公司",
        "contactTel": "15388655698",
        "email": "",
        "address": "",
        "roomId": "NH-EN-02",
        "complaintTime": "2020-09-25 17:55:09",
        "disposeTypeCode": "0",
        "evaluateCode": null,
        "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
        "createTime": "2020-09-25 17:55:09",
        "updateTime": "2020-09-25 17:55:09",
        "deleted": 0,
        "complaintAttachments": [],
        "complaintFeedback": null,
        "roomName": "NH-EN-02",
    }
