export const apportinList: any =
    {
        "content": [
            {
                "id": "mvfblncdyjcpyajhwjzjllub",
                "rdId": "8bd557d8904344fcb7876c25b431b1c1",
                "ruleId": "citfddkbculwxaslghridosm",
                "projectTypeCode": "2",
                "projectId": "jrtxmywzwdbwrasscztosaii",
                "psId": "yyyirkrhbsqgyktsgrqusfyo",
                "roomNum": 4,
                "payStartDate": "2020-08-28",
                "payEndDate": "2020-09-22",
                "originalAp": 300,
                "sharedRadio": 1,
                "totalAp": 300,
                "chargingDate": "2020-11",
                "billingDate": null,
                "remark": null,
                "sharedBillingStatusCode": "1",
                "totalMeterReading": null,
                "sharedPayTypeCode": "1",
                "meterReadingId": null,
                "payableDate": null,
                "createTime": "2020-08-17 14:55:01",
                "updateTime": "2020-08-17 19:28:21",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "rdName": "kk",
                "ruleName": "0817第二个公摊设定",
                "projectName": "水费",
                "meterReading": null
            },
            {
                "id": "upmdmvvmhyfrntybwbtwppde",
                "rdId": "jpuqmklzswvfxdpulahebftq",
                "ruleId": "ztvhtzgjskbkbuzudiodhkug",
                "projectTypeCode": "2",
                "projectId": "uvikuskmhhbbxryfdtvzfwwi",
                "psId": "wzftkoauhqftzbrmtcdalvtr",
                "roomNum": 2,
                "payStartDate": "2020-09-15",
                "payEndDate": "2020-10-13",
                "originalAp": 200,
                "sharedRadio": 1,
                "totalAp": 200,
                "chargingDate": "2020-10",
                "billingDate": "2020-09-16",
                "remark": null,
                "sharedBillingStatusCode": "2",
                "totalMeterReading": null,
                "sharedPayTypeCode": "1",
                "meterReadingId": null,
                "payableDate": "2020-09-19",
                "createTime": "2020-09-16 14:34:57",
                "updateTime": "2020-09-16 14:35:08",
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "updatePerson": "qdsljfxnlwcrsiyyexapfkxm",
                "deleted": 0,
                "rdName": "TEST07",
                "ruleName": "走表公摊222",
                "projectName": "水费",
                "meterReading": null
            },
            {
                "id": "baimdcdoofdlqlmpbfxwmdgd",
                "rdId": "8bd557d8904344fcb7876c25b431b1c1",
                "ruleId": "zjxahquuouwxxilbjifeuxgk",
                "projectTypeCode": "2",
                "projectId": "jrtxmywzwdbwrasscztosaii",
                "psId": "yyyirkrhbsqgyktsgrqusfyo",
                "roomNum": 0,
                "payStartDate": "2020-08-11",
                "payEndDate": "2020-09-17",
                "originalAp": 100,
                "sharedRadio": 1,
                "totalAp": 100,
                "chargingDate": "2020-09",
                "billingDate": null,
                "remark": null,
                "sharedBillingStatusCode": "0",
                "totalMeterReading": null,
                "sharedPayTypeCode": "1",
                "meterReadingId": null,
                "payableDate": null,
                "createTime": "2020-08-17 14:25:39",
                "updateTime": "2020-08-17 14:25:39",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "rdName": "kk",
                "ruleName": "0817公摊设定新增",
                "projectName": "水费",
                "meterReading": null
            },
            {
                "id": "xgpdhowccfkzjuylzkoqthvk",
                "rdId": "8bd557d8904344fcb7876c25b431b1c1",
                "ruleId": "zjxahquuouwxxilbjifeuxgk",
                "projectTypeCode": "3",
                "projectId": "jrtxmywzwdbwrasscztosaii",
                "psId": "yyyirkrhbsqgyktsgrqusfyo",
                "roomNum": 0,
                "payStartDate": "2020-08-05",
                "payEndDate": "2020-08-20",
                "originalAp": 13.33,
                "sharedRadio": 1,
                "totalAp": 13.33,
                "chargingDate": "2020-09",
                "billingDate": null,
                "remark": null,
                "sharedBillingStatusCode": "0",
                "totalMeterReading": null,
                "sharedPayTypeCode": "",
                "meterReadingId": null,
                "payableDate": null,
                "createTime": "2020-08-17 16:51:13",
                "updateTime": "2020-08-17 16:51:13",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "rdName": "kk",
                "ruleName": "0817公摊设定新增",
                "projectName": "水费",
                "meterReading": null
            },
            {
                "id": "bsdibppffbsqemjlfygxhwao",
                "rdId": "8bd557d8904344fcb7876c25b431b1c1",
                "ruleId": "eyrqgqiaxvpzrnfkoafkxfgg",
                "projectTypeCode": "3",
                "projectId": "jrtxmywzwdbwrasscztosaii",
                "psId": "vzgnyvhykexsfbkffqryzqri",
                "roomNum": 0,
                "payStartDate": "2020-08-14",
                "payEndDate": "2020-09-15",
                "originalAp": 13,
                "sharedRadio": 1.023,
                "totalAp": 13.3,
                "chargingDate": "2020-09",
                "billingDate": null,
                "remark": null,
                "sharedBillingStatusCode": "0",
                "totalMeterReading": null,
                "sharedPayTypeCode": "",
                "meterReadingId": null,
                "payableDate": null,
                "createTime": "2020-08-14 17:15:02",
                "updateTime": "2020-08-14 17:15:02",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "rdName": "kk",
                "ruleName": "电梯半阳",
                "projectName": "水费",
                "meterReading": null
            },
            {
                "id": "srrrtyctecqzpjeeozdqtkas",
                "rdId": "GLC0000005",
                "ruleId": "cdirugxrpzieqdmzxcgpufkp",
                "projectTypeCode": "3",
                "projectId": "cyavzugrstelttuzqryusycb",
                "psId": "sipywidvesrszvhwljrkmjhb",
                "roomNum": 16,
                "payStartDate": "2020-05-01",
                "payEndDate": "2020-08-01",
                "originalAp": 200,
                "sharedRadio": 1.1423,
                "totalAp": 228.46,
                "chargingDate": "2020-09",
                "billingDate": null,
                "remark": "备注",
                "sharedBillingStatusCode": "1",
                "totalMeterReading": null,
                "sharedPayTypeCode": "1",
                "meterReadingId": null,
                "payableDate": null,
                "createTime": "2020-08-14 18:06:21",
                "updateTime": "2020-08-17 16:50:28",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "rdName": "朝阳明居",
                "ruleName": "绿化公摊",
                "projectName": "绿化费用",
                "meterReading": null
            },
            {
                "id": "thjgipoektvrbivpzturhmla",
                "rdId": "GLC0000005",
                "ruleId": "cdirugxrpzieqdmzxcgpufkp",
                "projectTypeCode": "3",
                "projectId": "cyavzugrstelttuzqryusycb",
                "psId": "sipywidvesrszvhwljrkmjhb",
                "roomNum": 16,
                "payStartDate": "2020-05-01",
                "payEndDate": "2020-08-01",
                "originalAp": 200,
                "sharedRadio": 1.1423,
                "totalAp": 228.46,
                "chargingDate": "2020-09",
                "billingDate": null,
                "remark": "备注",
                "sharedBillingStatusCode": "1",
                "totalMeterReading": null,
                "sharedPayTypeCode": "1",
                "meterReadingId": null,
                "payableDate": null,
                "createTime": "2020-08-14 15:39:04",
                "updateTime": "2020-08-14 15:42:11",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "rdName": "朝阳明居",
                "ruleName": "绿化公摊",
                "projectName": "绿化费用",
                "meterReading": null
            },
            {
                "id": "mrnsulnippfyqgxntawskyoa",
                "rdId": "igtxmbrxnbcjuogapfeubuys",
                "ruleId": "onehftgrirmasqxcavkqviut",
                "projectTypeCode": "2",
                "projectId": "spqeamzyfaiizpwbdmxjirnd",
                "psId": "phidnksbfbxulgleszuajffu",
                "roomNum": 3,
                "payStartDate": "2020-09-01",
                "payEndDate": "2020-10-07",
                "originalAp": 100,
                "sharedRadio": 1,
                "totalAp": 100,
                "chargingDate": "2020-09",
                "billingDate": null,
                "remark": null,
                "sharedBillingStatusCode": "1",
                "totalMeterReading": null,
                "sharedPayTypeCode": "1",
                "meterReadingId": null,
                "payableDate": null,
                "createTime": "2020-09-01 22:50:29",
                "updateTime": "2020-09-01 23:11:02",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "rdName": "0817小区添加测试",
                "ruleName": "公摊测试0901",
                "projectName": "水费",
                "meterReading": null
            },
            {
                "id": "ugiznidezzxqvtkcovefzvhv",
                "rdId": "GLC0000005",
                "ruleId": "cdirugxrpzieqdmzxcgpufkp",
                "projectTypeCode": "3",
                "projectId": "cyavzugrstelttuzqryusycb",
                "psId": "sipywidvesrszvhwljrkmjhb",
                "roomNum": 16,
                "payStartDate": "2020-05-01",
                "payEndDate": "2020-08-01",
                "originalAp": 200,
                "sharedRadio": 1.1423,
                "totalAp": 228.46,
                "chargingDate": "2020-09",
                "billingDate": null,
                "remark": "备注",
                "sharedBillingStatusCode": "1",
                "totalMeterReading": null,
                "sharedPayTypeCode": "1",
                "meterReadingId": null,
                "payableDate": null,
                "createTime": "2020-08-14 17:14:06",
                "updateTime": "2020-08-25 17:04:31",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "rdName": "朝阳明居",
                "ruleName": "绿化公摊",
                "projectName": "绿化费用",
                "meterReading": null
            },
            {
                "id": "smegzwhhmtliwlyjemdsztli",
                "rdId": "GLC0000005",
                "ruleId": "cdirugxrpzieqdmzxcgpufkp",
                "projectTypeCode": "2",
                "projectId": "cyavzugrstelttuzqryusycb",
                "psId": "sipywidvesrszvhwljrkmjhb",
                "roomNum": 16,
                "payStartDate": "2020-08-11",
                "payEndDate": "2020-09-17",
                "originalAp": 200,
                "sharedRadio": 1.14,
                "totalAp": 228,
                "chargingDate": "2020-09",
                "billingDate": "2020-08-07",
                "remark": null,
                "sharedBillingStatusCode": "1",
                "totalMeterReading": null,
                "sharedPayTypeCode": "1",
                "meterReadingId": null,
                "payableDate": "2020-08-03",
                "createTime": "2020-08-05 13:30:53",
                "updateTime": "2020-08-07 13:50:57",
                "createPerson": "admin",
                "updatePerson": "admin",
                "deleted": 0,
                "rdName": "朝阳明居",
                "ruleName": "绿化公摊",
                "projectName": "绿化费用",
                "meterReading": null
            },
        ],
        totalElements: 21,
        totalPages: 2,
        numberOfElements: 11,
    }

export const apportinSetList: any =

    {
        "content": [
            {
                "id": "vkdombjzkxrhvojbctvnmlul",
                "name": "0922的公摊设定",
                "rdId": "jpuqmklzswvfxdpulahebftq",
                "projectTypeCode": "2",
                "projectId": "uvikuskmhhbbxryfdtvzfwwi",
                "psId": "zzmlixcfbqoyptfiyqrcvsud",
                "sharedTypeCode": "2",
                "sharedRadio": 0.8,
                "sortingNum": 1,
                "createTime": "2020-09-22 18:08:54",
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "updateTime": "2020-09-22 18:08:54",
                "updatePerson": "qdsljfxnlwcrsiyyexapfkxm",
                "deleted": 0,
                "projectName": "水费",
                "rdName": "TEST07"
            },
            {
                "id": "csmyncwofvvmuozwscypqahd",
                "name": "4564763",
                "rdId": "ynldtxtychcjjicwrakbnejo",
                "projectTypeCode": "3",
                "projectId": "zajmxrixuepdyoqmclwjfcxc",
                "psId": "sxociohbdkgfmipxhbbcfgtp",
                "sharedTypeCode": "2",
                "sharedRadio": 0.8,
                "sortingNum": 1,
                "createTime": "2020-09-16 17:28:49",
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "updateTime": "2020-09-16 17:28:49",
                "updatePerson": "qdsljfxnlwcrsiyyexapfkxm",
                "deleted": 0,
                "projectName": "0916收费项目3",
                "rdName": "TEST05"
            },
            {
                "id": "ztvhtzgjskbkbuzudiodhkug",
                "name": "走表公摊222",
                "rdId": "jpuqmklzswvfxdpulahebftq",
                "projectTypeCode": "2",
                "projectId": "uvikuskmhhbbxryfdtvzfwwi",
                "psId": "wzftkoauhqftzbrmtcdalvtr",
                "sharedTypeCode": "1",
                "sharedRadio": 1,
                "sortingNum": 1,
                "createTime": "2020-09-16 14:34:24",
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "updateTime": "2020-09-16 14:34:24",
                "updatePerson": "qdsljfxnlwcrsiyyexapfkxm",
                "deleted": 0,
                "projectName": "水费",
                "rdName": "TEST07"
            },
            {
                "id": "pcgzmvrgbvsmntmruvbnszgy",
                "name": "走表公摊1",
                "rdId": "jpuqmklzswvfxdpulahebftq",
                "projectTypeCode": "2",
                "projectId": "uvikuskmhhbbxryfdtvzfwwi",
                "psId": "qwystxaeeydgnpqmkrzyyfep",
                "sharedTypeCode": "2",
                "sharedRadio": 1,
                "sortingNum": 1,
                "createTime": "2020-09-16 13:41:29",
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "updateTime": "2020-09-16 13:41:29",
                "updatePerson": "qdsljfxnlwcrsiyyexapfkxm",
                "deleted": 0,
                "projectName": "水费",
                "rdName": "TEST07"
            },
            {
                "id": "idkbdcopylvpqrbnqdiuucpt",
                "name": "33333",
                "rdId": "jpuqmklzswvfxdpulahebftq",
                "projectTypeCode": "3",
                "projectId": "upaiontloatvqvingtgvcuic",
                "psId": "uitxkgawupzaqqnkbmgqyjix",
                "sharedTypeCode": "1",
                "sharedRadio": 1,
                "sortingNum": 1,
                "createTime": "2020-09-16 13:28:14",
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "updateTime": "2020-09-16 13:28:14",
                "updatePerson": "qdsljfxnlwcrsiyyexapfkxm",
                "deleted": 0,
                "projectName": "绿化公摊",
                "rdName": "TEST07"
            },
            {
                "id": "xtybbxbbgiofynfvnjysrexy",
                "name": "1111",
                "rdId": "jpuqmklzswvfxdpulahebftq",
                "projectTypeCode": "3",
                "projectId": "upaiontloatvqvingtgvcuic",
                "psId": "zgkdeirznujlzembodzdyjty",
                "sharedTypeCode": "1",
                "sharedRadio": 1,
                "sortingNum": 1,
                "createTime": "2020-09-16 11:34:00",
                "createPerson": "qdsljfxnlwcrsiyyexapfkxm",
                "updateTime": "2020-09-16 11:34:00",
                "updatePerson": "qdsljfxnlwcrsiyyexapfkxm",
                "deleted": 0,
                "projectName": "绿化公摊",
                "rdName": "TEST07"
            },
            {
                "id": "onehftgrirmasqxcavkqviut",
                "name": "公摊测试0901",
                "rdId": "igtxmbrxnbcjuogapfeubuys",
                "projectTypeCode": "2",
                "projectId": "spqeamzyfaiizpwbdmxjirnd",
                "psId": "phidnksbfbxulgleszuajffu",
                "sharedTypeCode": "1",
                "sharedRadio": 1,
                "sortingNum": 1,
                "createTime": "2020-09-01 22:49:28",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updateTime": "2020-09-01 22:49:28",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "projectName": "水费",
                "rdName": "0817小区添加测试"
            },
            {
                "id": "limvayaysqktpsjsbqswshzg",
                "name": "0817",
                "rdId": "igtxmbrxnbcjuogapfeubuys",
                "projectTypeCode": "2",
                "projectId": "spqeamzyfaiizpwbdmxjirnd",
                "psId": "phidnksbfbxulgleszuajffu",
                "sharedTypeCode": "1",
                "sharedRadio": 0.1,
                "sortingNum": 1,
                "createTime": "2020-08-31 16:43:19",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updateTime": "2020-08-31 16:48:37",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "projectName": "水费",
                "rdName": "0817小区添加测试"
            },
            {
                "id": "loldfheefrtdzuhaovntksid",
                "name": "for3302",
                "rdId": "erpeisaziwhfxtzjazcakqyr",
                "projectTypeCode": "2",
                "projectId": "cbbhlzwpyzfsjqwigchmubnf",
                "psId": "hxlgdizcnbtvjawobuawogsx",
                "sharedTypeCode": "1",
                "sharedRadio": 1,
                "sortingNum": 1,
                "createTime": "2020-08-31 14:33:06",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updateTime": "2020-08-31 14:33:06",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "projectName": "电费",
                "rdName": "ZZ"
            },
            {
                "id": "suajkhjqixpxqbjxtrprsmxp",
                "name": "滞纳金谈谈谈",
                "rdId": "GLC0000003",
                "projectTypeCode": "3",
                "projectId": "ewunrkpkuhmmsggtormjsgps",
                "psId": "qxclzbxpeeawedifcfsojxpn",
                "sharedTypeCode": "1",
                "sharedRadio": 1.033,
                "sortingNum": 1,
                "createTime": "2020-08-28 15:10:28",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updateTime": "2020-08-28 15:10:28",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "projectName": "绿化公摊",
                "rdName": "红山小区"
            },
            {
                "id": "rylxtfsnmjwhpzngbfcervkb",
                "name": "物业公摊",
                "rdId": "erpeisaziwhfxtzjazcakqyr",
                "projectTypeCode": "3",
                "projectId": "xoeuktjiwapboezjwkocvsph",
                "psId": "vxjuywrlczpfbmhnreofgqxh",
                "sharedTypeCode": "1",
                "sharedRadio": 1,
                "sortingNum": 1,
                "createTime": "2020-08-25 16:17:34",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updateTime": "2020-08-28 15:09:00",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "projectName": "水费",
                "rdName": "ZZ"
            },
            {
                "id": "sieorqqmnyikbmkxcwodwmkp",
                "name": "ZZ的第二个公摊设定",
                "rdId": "erpeisaziwhfxtzjazcakqyr",
                "projectTypeCode": "2",
                "projectId": "cbbhlzwpyzfsjqwigchmubnf",
                "psId": "hxlgdizcnbtvjawobuawogsx",
                "sharedTypeCode": "1",
                "sharedRadio": 1,
                "sortingNum": 1,
                "createTime": "2020-08-25 17:26:06",
                "createPerson": "566045cbdd621dff8c0f6bc1",
                "updateTime": "2020-08-28 14:58:14",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "projectName": "电费",
                "rdName": "ZZ"
            }
        ],
        "pageable": {
            "sort": {
                "sorted": false,
                "unsorted": true,
                "empty": true
            },
            "pageNumber": 0,
            "pageSize": 12,
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "totalElements": 22,
        "totalPages": 2,
        "last": false,
        "sort": {
            "sorted": false,
            "unsorted": true,
            "empty": true
        },
        "numberOfElements": 12,
        "first": true,
        "size": 12,
        "number": 0,
        "empty": false
    }

