export const orgList: any =
    [
        {
            "id": "GLC0000001",
            "title": "南湖小区",
            "parentId": null,
            "expand": false,
            "belongNum": 3,
            "level": 1,
            "checked": false,
            "property": null,
            "children": []
        },
        {
            "id": "GLC0000002",
            "title": "如意苑",
            "parentId": null,
            "expand": false,
            "belongNum": 0,
            "level": 1,
            "checked": false,
            "property": null,
            "children": []
        },
        {
            "id": "GLC0000003",
            "title": "红山小区",
            "parentId": null,
            "expand": false,
            "belongNum": 6,
            "level": 1,
            "checked": false,
            "property": null,
            "children": []
        },
        {
            "id": "GLC0000004",
            "title": "城建大厦",
            "parentId": null,
            "expand": false,
            "belongNum": 0,
            "level": 1,
            "checked": false,
            "property": null,
            "children": []
        },
        {
            "id": "GLC0000005",
            "title": "朝阳明居",
            "parentId": null,
            "expand": false,
            "belongNum": 3,
            "level": 1,
            "checked": false,
            "property": null,
            "children": []
        },


    ]

export const staList: any =
    [
        {
            "id": "f078ea5a58074e8aaca0d201084a456a",
            "name": "垃圾费",
            "projectTypeCode": "3",
            "projectCode": "LJF",
            "description": "这是垃圾费",
            "lateFeeNeed": 0,
            "lateFeeRate": 0,
            "rdId": "GLC0000003",
            "sortingNum": 30,
            "enabled": 1,
            "createTime": "2020-07-15 17:49:22",
            "createPerson": "",
            "updateTime": "2020-07-15 17:49:22",
            "updatePerson": "",
            "deleted": 0,
            "standardCount": 2,
            "level": 2
        },
        {
            "id": "f88172a1a69e4cf8b38967f866089617",
            "name": "物业费",
            "projectTypeCode": "1",
            "projectCode": "wuyf",
            "description": "",
            "lateFeeNeed": 1,
            "lateFeeRate": 1.3,
            "rdId": "GLC0000003",
            "sortingNum": 35,
            "enabled": 1,
            "createTime": "2020-07-20 10:58:00",
            "createPerson": "",
            "updateTime": "2020-08-18 11:13:34",
            "updatePerson": "566045cbdd621dff8c0f6bc1",
            "deleted": 0,
            "standardCount": 4,
            "level": 2
        },
        {
            "id": "03898e301fc64e2491f85204df274fae",
            "name": "门禁电梯费",
            "projectTypeCode": "3",
            "projectCode": "ttt",
            "description": "",
            "lateFeeNeed": 0,
            "lateFeeRate": 0,
            "rdId": "GLC0000003",
            "sortingNum": 36,
            "enabled": 1,
            "createTime": "2020-07-20 10:59:48",
            "createPerson": "",
            "updateTime": "2020-07-20 10:59:48",
            "updatePerson": "",
            "deleted": 0,
            "standardCount": 1,
            "level": 2
        },
        {
            "id": "xoeuktjiwapboezjwkocvsph",
            "name": "水费",
            "projectTypeCode": "2",
            "projectCode": "shuifei",
            "description": "",
            "lateFeeNeed": 1,
            "lateFeeRate": 0.123,
            "rdId": "GLC0000003",
            "sortingNum": 40,
            "enabled": 1,
            "createTime": "2020-07-27 15:25:11",
            "createPerson": "",
            "updateTime": "2020-09-09 15:13:50",
            "updatePerson": "566045cbdd621dff8c0f6bc1",
            "deleted": 0,
            "standardCount": 5,
            "level": 2
        },
        {
            "id": "ewunrkpkuhmmsggtormjsgps",
            "name": "绿化公摊",
            "projectTypeCode": "3",
            "projectCode": "lvhua",
            "description": "",
            "lateFeeNeed": 0,
            "lateFeeRate": 0,
            "rdId": "GLC0000003",
            "sortingNum": 43,
            "enabled": 1,
            "createTime": "2020-07-31 16:54:55",
            "createPerson": "",
            "updateTime": "2020-09-09 15:13:20",
            "updatePerson": "566045cbdd621dff8c0f6bc1",
            "deleted": 0,
            "standardCount": 1,
            "level": 2
        },
        {
            "id": "cbwbsdlccgszgdgyadmbnfrh",
            "name": "电费",
            "projectTypeCode": "2",
            "projectCode": "df",
            "description": "",
            "lateFeeNeed": 0,
            "lateFeeRate": 0,
            "rdId": "GLC0000003",
            "sortingNum": 72,
            "enabled": 1,
            "createTime": "2020-08-17 17:03:26",
            "createPerson": "566045cbdd621dff8c0f6bc1",
            "updateTime": "2020-08-17 17:03:26",
            "updatePerson": "566045cbdd621dff8c0f6bc1",
            "deleted": 0,
            "standardCount": 1,
            "level": 2
        }
    ]
