export const organizationList: any[] = [
    {
        "id": "GLC0000001",
        "title": "南湖小区",
        "parentId": null,
        "expand": true,
        "belongNum": 5,
        "level": 1,
        "checked": false,
        "property": null,
        "children": [
            {
                "id": "DLDM000013",
                "title": "01号楼",
                "parentId": "GLC0000001",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 1
            },
            {
                "id": "DLDM000014",
                "title": "02号楼",
                "parentId": "GLC0000001",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 2
            },
            {
                "id": "DLDM000015",
                "title": "办公楼",
                "parentId": "GLC0000001",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 3
            },
            {
                "id": "DLDM000031",
                "title": "南湖小区车库",
                "parentId": "GLC0000001",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 4
            },
            {
                "id": "DLDM000312",
                "title": "水区交警队",
                "parentId": "GLC0000001",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 5
            }
        ],
        "nodeKey": 0
    },
    {
        "id": "GLC0000002",
        "title": "如意苑",
        "parentId": null,
        "expand": false,
        "belongNum": 8,
        "level": 1,
        "checked": false,
        "property": null,
        "children": [{
            "id": "DLDM000016",
            "title": "01号楼",
            "parentId": "GLC0000002",
            "expand": false,
            "belongNum": 0,
            "level": 2,
            "checked": false,
            "property": null,
            "children": [],
            "nodeKey": 7
        },
            {
                "id": "DLDM000017",
                "title": "02号楼",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 8
            },
            {
                "id": "DLDM000018",
                "title": "03号楼",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 9
            },
            {
                "id": "DLDM000019",
                "title": "04号楼",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 10
            },
            {
                "id": "DLDM000020",
                "title": "05号楼",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 11
            },
            {
                "id": "DLDM000021",
                "title": "06号楼",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 12
            },
            {
                "id": "DLDM000030",
                "title": "如意苑门面房",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 13
            },
            {
                "id": "DLDM000199",
                "title": "如意苑小区01号楼商铺",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 14
            }
        ],
        "nodeKey": 6
    },
    {
        "id": "GLC0000003",
        "title": "红山小区",
        "parentId": null,
        "expand": false,
        "belongNum": 7,
        "level": 1,
        "checked": false,
        "property": null,
        "children": [{
            "id": "DLDM000023",
            "title": "04号楼",
            "parentId": "GLC0000003",
            "expand": false,
            "belongNum": 0,
            "level": 2,
            "checked": false,
            "property": null,
            "children": [],
            "nodeKey": 16
        },
            {
                "id": "DLDM000024",
                "title": "05号楼",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 17
            },
            {
                "id": "DLDM000025",
                "title": "06号楼",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 18
            },
            {
                "id": "DLDM000026",
                "title": "04商铺",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 19
            },
            {
                "id": "DLDM000027",
                "title": "阿勒泰路35楼",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 20
            },
            {
                "id": "DLDM000028",
                "title": "阿勒泰35号楼商铺",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 21
            },
            {
                "id": "DLDM000029",
                "title": "红山路05号楼",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 22
            }
        ],
        "nodeKey": 15
    },
    {
        "id": "GLC0000004",
        "title": "城建大厦",
        "parentId": null,
        "expand": false,
        "belongNum": 3,
        "level": 1,
        "checked": false,
        "property": null,
        "children": [{
            "id": "DLDM000008",
            "title": "城建大厦",
            "parentId": "GLC0000004",
            "expand": false,
            "belongNum": 0,
            "level": 2,
            "checked": false,
            "property": null,
            "children": [],
            "nodeKey": 24
        },
            {
                "id": "DLDM000187",
                "title": "上海市人民政府驻新疆办事处",
                "parentId": "GLC0000004",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 25
            },
            {
                "id": "DLDM000226",
                "title": "乌鲁木齐市地方税务局稽查局",
                "parentId": "GLC0000004",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 26
            }
        ],
        "nodeKey": 23
    },
]

export const buildingList: any = {
    "content": [
        {
            "id": "DLDM000013",
            "name": "01号楼",
            "code": "-1",
            "longitude": 0,
            "latitude": 0,
            "rdId": "GLC0000001",
            "upFloorNum": 0,
            "height": 0,
            "underFloorNum": 0,
            "buildingPicId": "",
            "sortingNum": 1,
            "createTime": "2020-07-01 19:23:06",
            "createPerson": "",
            "updateTime": "2020-07-01 19:23:06",
            "updatePerson": "",
            "deleted": 0,
            "unitCount": 0,
            "prNumber": 0,
            "roomCount": 0
        },
        {
            "id": "DLDM000014",
            "name": "02号楼",
            "code": "-2",
            "longitude": 0,
            "latitude": 0,
            "rdId": "GLC0000001",
            "upFloorNum": 0,
            "height": 0,
            "underFloorNum": 0,
            "buildingPicId": "",
            "sortingNum": 2,
            "createTime": "2020-07-01 19:23:06",
            "createPerson": "",
            "updateTime": "2020-07-01 19:23:06",
            "updatePerson": "",
            "deleted": 0,
            "unitCount": 0,
            "prNumber": 0,
            "roomCount": 0
        },
        {
            "id": "DLDM000015",
            "name": "办公楼",
            "code": "-3",
            "longitude": 0,
            "latitude": 0,
            "rdId": "GLC0000001",
            "upFloorNum": 0,
            "height": 0,
            "underFloorNum": 0,
            "buildingPicId": "",
            "sortingNum": 3,
            "createTime": "2020-07-01 19:23:06",
            "createPerson": "",
            "updateTime": "2020-07-01 19:23:06",
            "updatePerson": "",
            "deleted": 0,
            "unitCount": 0,
            "prNumber": 0,
            "roomCount": 0
        },
        {
            "id": "DLDM000031",
            "name": "南湖小区车库",
            "code": "－CK",
            "longitude": 0,
            "latitude": 0,
            "rdId": "GLC0000001",
            "upFloorNum": 0,
            "height": 0,
            "underFloorNum": 0,
            "buildingPicId": "",
            "sortingNum": 4,
            "createTime": "2020-07-01 19:23:06",
            "createPerson": "",
            "updateTime": "2020-07-01 19:23:06",
            "updatePerson": "",
            "deleted": 0,
            "unitCount": 0,
            "prNumber": 0,
            "roomCount": 0
        },
        {
            "id": "DLDM000312",
            "name": "水区交警队",
            "code": "SQJYD",
            "longitude": 0,
            "latitude": 0,
            "rdId": "GLC0000001",
            "upFloorNum": 0,
            "height": 0,
            "underFloorNum": 0,
            "buildingPicId": "",
            "sortingNum": 5,
            "createTime": "2020-07-01 19:23:06",
            "createPerson": "",
            "updateTime": "2020-07-01 19:23:06",
            "updatePerson": "",
            "deleted": 0,
            "unitCount": 0,
            "prNumber": 0,
            "roomCount": 0
        }
    ],
    "pageable": {
        "sort": {
            "sorted": false,
            "unsorted": true,
            "empty": true
        },
        "pageNumber": 0,
        "pageSize": 10,
        "offset": 0,
        "paged": true,
        "unpaged": false
    },
    "totalPages": 1,
    "totalElements": 5,
    "last": true,
    "sort": {
        "sorted": false,
        "unsorted": true,
        "empty": true
    },
    "numberOfElements": 5,
    "first": true,
    "size": 10,
    "number": 0,
    "empty": false
}

export const organizationPage: any =
    {
        "content": [{
            "id": "GLC0000001",
            "name": "南湖小区",
            "address": "",
            "developer": "新疆城建股份有限公司",
            "property": "新疆城建物业管理有限公司",
            "buildingNum": 5,
            "prNumber": 134,
            "code": "NH",
            "longitude": 0,
            "latitude": 0,
            "communityId": "",
            "rdPicId": "165",
            "sortingNum": 1,
            "createTime": "2020-08-18 19:44:32",
            "createPerson": "系统管理员",
            "updateTime": "2020-10-28 14:10:19",
            "updatePerson": "566045cbdd621dff8c0f6bc1",
            "deleted": 0,
            "regionCode": 650100
        },
            {
                "id": "GLC0000002",
                "name": "如意苑",
                "address": "",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "RYY",
                "longitude": 0,
                "latitude": 0,
                "communityId": "",
                "rdPicId": "",
                "sortingNum": 2,
                "createTime": "2020-08-18 19:44:32",
                "createPerson": "系统管理员",
                "updateTime": "2020-08-18 19:52:58",
                "updatePerson": "",
                "deleted": 0,
                "regionCode": 650100
            },
            {
                "id": "GLC0000003",
                "name": "红山小区",
                "address": "",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "HS",
                "longitude": 0,
                "latitude": 0,
                "communityId": "",
                "rdPicId": "",
                "sortingNum": 3,
                "createTime": "2020-08-18 19:44:32",
                "createPerson": "系统管理员",
                "updateTime": "2020-08-18 19:52:58",
                "updatePerson": "",
                "deleted": 0,
                "regionCode": 650100
            },
            {
                "id": "GLC0000004",
                "name": "城建大厦",
                "address": "新疆乌鲁木齐市东大梁路",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "CJDS",
                "longitude": 0,
                "latitude": 0,
                "communityId": "",
                "rdPicId": "",
                "sortingNum": 4,
                "createTime": "2020-08-18 19:44:32",
                "createPerson": "系统管理员",
                "updateTime": "2020-08-18 19:52:58",
                "updatePerson": "",
                "deleted": 0,
                "regionCode": 650100
            },
            {
                "id": "GLC0000005",
                "name": "朝阳明居",
                "address": "",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "ZYMJ",
                "longitude": 0,
                "latitude": 0,
                "communityId": "",
                "rdPicId": "",
                "sortingNum": 5,
                "createTime": "2020-08-18 19:44:32",
                "createPerson": "",
                "updateTime": "2020-08-18 19:52:59",
                "updatePerson": "",
                "deleted": 0,
                "regionCode": 650100
            },
            {
                "id": "GLC0000006",
                "name": "办公室",
                "address": "",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "BGS",
                "longitude": 0,
                "latitude": 0,
                "communityId": "",
                "rdPicId": "",
                "sortingNum": 6,
                "createTime": "2020-08-18 19:44:32",
                "createPerson": "系统管理员",
                "updateTime": "2020-08-18 19:52:59",
                "updatePerson": "",
                "deleted": 0,
                "regionCode": 650100
            },
            {
                "id": "GLC0000007",
                "name": "朗天峰景",
                "address": "",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "LTFJ",
                "longitude": 0,
                "latitude": 0,
                "communityId": "",
                "rdPicId": "",
                "sortingNum": 7,
                "createTime": "2020-08-18 19:44:32",
                "createPerson": "admin",
                "updateTime": "2020-08-18 19:52:59",
                "updatePerson": "",
                "deleted": 0,
                "regionCode": 650100
            },
            {
                "id": "GLC0000008",
                "name": "西山小区",
                "address": "",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "XS",
                "longitude": 0,
                "latitude": 0,
                "communityId": "",
                "rdPicId": "",
                "sortingNum": 8,
                "createTime": "2020-08-18 19:44:32",
                "createPerson": "admin",
                "updateTime": "2020-08-18 19:52:59",
                "updatePerson": "",
                "deleted": 0,
                "regionCode": 650100
            },
            {
                "id": "GLC0000009",
                "name": "朗月星城",
                "address": "",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "LYXC",
                "longitude": 0,
                "latitude": 0,
                "communityId": "",
                "rdPicId": "",
                "sortingNum": 9,
                "createTime": "2020-08-18 19:44:32",
                "createPerson": "admin",
                "updateTime": "2020-08-18 19:52:59",
                "updatePerson": "",
                "deleted": 0,
                "regionCode": 650100
            },
            {
                "id": "GLC0000011",
                "name": "朗天峰景二期",
                "address": "",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "LTFJ2",
                "longitude": 0,
                "latitude": 0,
                "communityId": "",
                "rdPicId": "",
                "sortingNum": 10,
                "createTime": "2020-08-18 19:44:32",
                "createPerson": "admin",
                "updateTime": "2020-08-18 19:52:59",
                "updatePerson": "",
                "deleted": 0,
                "regionCode": 650100
            },
            {
                "id": "2340e44c51f644cebe2dd2a51650874b",
                "name": "康城果岭小区",
                "address": "乌鲁木齐市新市区",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "KCGL",
                "longitude": 0,
                "latitude": 0,
                "communityId": "8292f053a17748a2b0c023577b610033",
                "rdPicId": "",
                "sortingNum": 11,
                "createTime": "2020-07-20 20:24:20",
                "createPerson": "admin",
                "updateTime": "2020-08-27 10:51:51",
                "updatePerson": "566045cbdd621dff8c0f6bc1",
                "deleted": 0,
                "regionCode": 650100
            },
            {
                "id": "GLC0000012",
                "name": "沁馨园",
                "address": "",
                "developer": "新疆城建股份有限公司",
                "property": "新疆城建物业管理有限公司",
                "buildingNum": 0,
                "prNumber": 0,
                "code": "qxy",
                "longitude": 0,
                "latitude": 0,
                "communityId": "",
                "rdPicId": "",
                "sortingNum": 12,
                "createTime": "2020-08-18 19:44:32",
                "createPerson": "admin",
                "updateTime": "2020-08-18 19:52:59",
                "updatePerson": "",
                "deleted": 0,
                "regionCode": 650100
            }
        ],
        "pageable": {
            "sort": {
                "sorted": false,
                "unsorted": true,
                "empty": true
            },
            "pageNumber": 0,
            "pageSize": 12,
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "totalPages": 5,
        "totalElements": 55,
        "last": false,
        "sort": {
            "sorted": false,
            "unsorted": true,
            "empty": true
        },
        "numberOfElements": 12,
        "first": true,
        "size": 12,
        "number": 0,
        "empty": false
    }

export const roomList: any =
    {
        "content": [
            {
                "id": "NH-1-1-101",
                "roomNum": "101",
                "name": "NH-1-1-101",
                "buildArea": 105.06,
                "useArea": 0,
                "roomTypeCode": null,
                "roomTowardsCode": null,
                "roomStatusCode": null,
                "roomConstructCode": null,
                "roomUsageTypeCode": null,
                "floorNum": 1,
                "buildingName": "01号楼",
                "unitName": "1",
                "roomPicId": null,
                "rdId": "GLC0000001",
                "buildingId": "DLDM000013",
                "unitId": "1",
                "floorId": "1"
            },
            {
                "id": "NH-1-1-102",
                "roomNum": "102",
                "name": "NH-1-1-102",
                "buildArea": 104.63,
                "useArea": 0,
                "roomTypeCode": null,
                "roomTowardsCode": null,
                "roomStatusCode": null,
                "roomConstructCode": null,
                "roomUsageTypeCode": null,
                "floorNum": 1,
                "buildingName": "01号楼",
                "unitName": "1",
                "roomPicId": null,
                "rdId": "GLC0000001",
                "buildingId": "DLDM000013",
                "unitId": "1",
                "floorId": "1"
            },
            {
                "id": "NH-1-1-201",
                "roomNum": "201",
                "name": "NH-1-1-201",
                "buildArea": 105.06,
                "useArea": 0,
                "roomTypeCode": null,
                "roomTowardsCode": null,
                "roomStatusCode": null,
                "roomConstructCode": null,
                "roomUsageTypeCode": null,
                "floorNum": 1,
                "buildingName": "01号楼",
                "unitName": "1",
                "roomPicId": null,
                "rdId": "GLC0000001",
                "buildingId": "DLDM000013",
                "unitId": "1",
                "floorId": "2"
            },
            {
                "id": "NH-1-1-202",
                "roomNum": "202",
                "name": "NH-1-1-202",
                "buildArea": 104.63,
                "useArea": 0,
                "roomTypeCode": null,
                "roomTowardsCode": null,
                "roomStatusCode": null,
                "roomConstructCode": null,
                "roomUsageTypeCode": null,
                "floorNum": 1,
                "buildingName": "01号楼",
                "unitName": "1",
                "roomPicId": null,
                "rdId": "GLC0000001",
                "buildingId": "DLDM000013",
                "unitId": "1",
                "floorId": "2"
            },
            {
                "id": "NH-1-1-301",
                "roomNum": "301",
                "name": "NH-1-1-301",
                "buildArea": 105.06,
                "useArea": 0,
                "roomTypeCode": null,
                "roomTowardsCode": null,
                "roomStatusCode": null,
                "roomConstructCode": null,
                "roomUsageTypeCode": null,
                "floorNum": 1,
                "buildingName": "01号楼",
                "unitName": "1",
                "roomPicId": null,
                "rdId": "GLC0000001",
                "buildingId": "DLDM000013",
                "unitId": "1",
                "floorId": "3"
            },
            {
                "id": "NH-1-1-302",
                "roomNum": "302",
                "name": "NH-1-1-302",
                "buildArea": 104.63,
                "useArea": 0,
                "roomTypeCode": null,
                "roomTowardsCode": null,
                "roomStatusCode": null,
                "roomConstructCode": null,
                "roomUsageTypeCode": null,
                "floorNum": 1,
                "buildingName": "01号楼",
                "unitName": "1",
                "roomPicId": null,
                "rdId": "GLC0000001",
                "buildingId": "DLDM000013",
                "unitId": "1",
                "floorId": "3"
            },
            {
                "id": "NH-1-1-401",
                "roomNum": "401",
                "name": "NH-1-1-401",
                "buildArea": 105.06,
                "useArea": 0,
                "roomTypeCode": null,
                "roomTowardsCode": null,
                "roomStatusCode": null,
                "roomConstructCode": null,
                "roomUsageTypeCode": null,
                "floorNum": 1,
                "buildingName": "01号楼",
                "unitName": "1",
                "roomPicId": null,
                "rdId": "GLC0000001",
                "buildingId": "DLDM000013",
                "unitId": "1",
                "floorId": "4"
            },
            {
                "id": "NH-1-1-402",
                "roomNum": "402",
                "name": "NH-1-1-402",
                "buildArea": 104.63,
                "useArea": 0,
                "roomTypeCode": null,
                "roomTowardsCode": null,
                "roomStatusCode": null,
                "roomConstructCode": null,
                "roomUsageTypeCode": null,
                "floorNum": 1,
                "buildingName": "01号楼",
                "unitName": "1",
                "roomPicId": null,
                "rdId": "GLC0000001",
                "buildingId": "DLDM000013",
                "unitId": "1",
                "floorId": "4"
            },
            {
                "id": "NH-1-1-501",
                "roomNum": "501",
                "name": "NH-1-1-501",
                "buildArea": 105.06,
                "useArea": 0,
                "roomTypeCode": null,
                "roomTowardsCode": null,
                "roomStatusCode": null,
                "roomConstructCode": null,
                "roomUsageTypeCode": null,
                "floorNum": 1,
                "buildingName": "01号楼",
                "unitName": "1",
                "roomPicId": null,
                "rdId": "GLC0000001",
                "buildingId": "DLDM000013",
                "unitId": "1",
                "floorId": "5"
            }
        ],
        "pageable": {
            "sort": {
                "sorted": false,
                "unsorted": true,
                "empty": true
            },
            "pageNumber": 0,
            "pageSize": 9,
            "offset": 0,
            "paged": true,
            "unpaged": false
        },
        "totalPages": 5,
        "totalElements": 44,
        "last": false,
        "sort": {
            "sorted": false,
            "unsorted": true,
            "empty": true
        },
        "numberOfElements": 9,
        "first": true,
        "size": 9,
        "number": 0,
        "empty": false
    }

export const citizenList: any =
{
    "content": [{
    "id": "353",
    "buildingId": "DLDM000013",
    "buildingName": "01号楼",
    "roomId": "NH-1-1-101",
    "roomNum": "101",
    "roomName": "NH-1-1-101",
    "personName": "王丹",
    "sexCode": "1",
    "birthday": null,
    "nationCode": "",
    "tel": "",
    "nativePlaceRegionCode": "",
    "time": "2020-07-07 10:50:08"
},
    {
        "id": "354",
        "buildingId": "DLDM000013",
        "buildingName": "01号楼",
        "roomId": "NH-1-1-102",
        "roomNum": "102",
        "roomName": "NH-1-1-102",
        "personName": "李敏",
        "sexCode": "1",
        "birthday": null,
        "nationCode": "",
        "tel": "",
        "nativePlaceRegionCode": "",
        "time": "2020-07-07 10:50:08"
    },
    {
        "id": "355",
        "buildingId": "DLDM000013",
        "buildingName": "01号楼",
        "roomId": "NH-1-1-201",
        "roomNum": "201",
        "roomName": "NH-1-1-201",
        "personName": "白秀英",
        "sexCode": "1",
        "birthday": null,
        "nationCode": "",
        "tel": "",
        "nativePlaceRegionCode": "",
        "time": "2020-07-07 10:50:08"
    },
    {
        "id": "356",
        "buildingId": "DLDM000013",
        "buildingName": "01号楼",
        "roomId": "NH-1-1-202",
        "roomNum": "202",
        "roomName": "NH-1-1-202",
        "personName": "张健斌",
        "sexCode": "1",
        "birthday": null,
        "nationCode": "",
        "tel": "",
        "nativePlaceRegionCode": "",
        "time": "2020-07-07 10:50:08"
    },
    {
        "id": "357",
        "buildingId": "DLDM000013",
        "buildingName": "01号楼",
        "roomId": "NH-1-1-301",
        "roomNum": "301",
        "roomName": "NH-1-1-301",
        "personName": "杨智",
        "sexCode": "1",
        "birthday": null,
        "nationCode": "",
        "tel": "",
        "nativePlaceRegionCode": "",
        "time": "2020-07-07 10:50:08"
    },
    {
        "id": "358",
        "buildingId": "DLDM000013",
        "buildingName": "01号楼",
        "roomId": "NH-1-1-302",
        "roomNum": "302",
        "roomName": "NH-1-1-302",
        "personName": "陈永华",
        "sexCode": "1",
        "birthday": null,
        "nationCode": "",
        "tel": "",
        "nativePlaceRegionCode": "",
        "time": "2020-07-07 10:50:08"
    },
    {
        "id": "359",
        "buildingId": "DLDM000013",
        "buildingName": "01号楼",
        "roomId": "NH-1-1-401",
        "roomNum": "401",
        "roomName": "NH-1-1-401",
        "personName": "陈如兰",
        "sexCode": "1",
        "birthday": null,
        "nationCode": "",
        "tel": "",
        "nativePlaceRegionCode": "",
        "time": "2020-07-07 10:50:08"
    },
    {
        "id": "360",
        "buildingId": "DLDM000013",
        "buildingName": "01号楼",
        "roomId": "NH-1-1-402",
        "roomNum": "402",
        "roomName": "NH-1-1-402",
        "personName": "李娜",
        "sexCode": "1",
        "birthday": null,
        "nationCode": "",
        "tel": "",
        "nativePlaceRegionCode": "",
        "time": "2020-07-07 10:50:08"
    }
],
    "pageable": {
    "sort": {
        "sorted": false,
            "unsorted": true,
            "empty": true
    },
    "pageNumber": 0,
        "pageSize": 8,
        "offset": 0,
        "paged": true,
        "unpaged": false
},
    "totalPages": 12,
    "totalElements": 92,
    "last": false,
    "sort": {
    "sorted": false,
        "unsorted": true,
        "empty": true
},
    "numberOfElements": 8,
    "first": true,
    "size": 8,
    "number": 0,
    "empty": false
}
