export const organizationList: any[] = [
    {
        "id": "GLC0000001",
        "title": "南湖小区",
        "parentId": null,
        "expand": true,
        "belongNum": 5,
        "level": 1,
        "checked": false,
        "property": null,
        "children": [
            {
                "id": "DLDM000013",
                "title": "01号楼",
                "parentId": "GLC0000001",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 1
            },
            {
                "id": "DLDM000014",
                "title": "02号楼",
                "parentId": "GLC0000001",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 2
            },
            {
                "id": "DLDM000015",
                "title": "办公楼",
                "parentId": "GLC0000001",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 3
            },
            {
                "id": "DLDM000031",
                "title": "南湖小区车库",
                "parentId": "GLC0000001",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 4
            },
            {
                "id": "DLDM000312",
                "title": "水区交警队",
                "parentId": "GLC0000001",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 5
            }
        ],
        "nodeKey": 0
    },
    {
        "id": "GLC0000002",
        "title": "如意苑",
        "parentId": null,
        "expand": false,
        "belongNum": 8,
        "level": 1,
        "checked": false,
        "property": null,
        "children": [{
            "id": "DLDM000016",
            "title": "01号楼",
            "parentId": "GLC0000002",
            "expand": false,
            "belongNum": 0,
            "level": 2,
            "checked": false,
            "property": null,
            "children": [],
            "nodeKey": 7
        },
            {
                "id": "DLDM000017",
                "title": "02号楼",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 8
            },
            {
                "id": "DLDM000018",
                "title": "03号楼",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 9
            },
            {
                "id": "DLDM000019",
                "title": "04号楼",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 10
            },
            {
                "id": "DLDM000020",
                "title": "05号楼",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 11
            },
            {
                "id": "DLDM000021",
                "title": "06号楼",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 12
            },
            {
                "id": "DLDM000030",
                "title": "如意苑门面房",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 13
            },
            {
                "id": "DLDM000199",
                "title": "如意苑小区01号楼商铺",
                "parentId": "GLC0000002",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 14
            }
        ],
        "nodeKey": 6
    },
    {
        "id": "GLC0000003",
        "title": "红山小区",
        "parentId": null,
        "expand": false,
        "belongNum": 7,
        "level": 1,
        "checked": false,
        "property": null,
        "children": [{
            "id": "DLDM000023",
            "title": "04号楼",
            "parentId": "GLC0000003",
            "expand": false,
            "belongNum": 0,
            "level": 2,
            "checked": false,
            "property": null,
            "children": [],
            "nodeKey": 16
        },
            {
                "id": "DLDM000024",
                "title": "05号楼",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 17
            },
            {
                "id": "DLDM000025",
                "title": "06号楼",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 18
            },
            {
                "id": "DLDM000026",
                "title": "04商铺",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 19
            },
            {
                "id": "DLDM000027",
                "title": "阿勒泰路35楼",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 20
            },
            {
                "id": "DLDM000028",
                "title": "阿勒泰35号楼商铺",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 21
            },
            {
                "id": "DLDM000029",
                "title": "红山路05号楼",
                "parentId": "GLC0000003",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 22
            }
        ],
        "nodeKey": 15
    },
    {
        "id": "GLC0000004",
        "title": "城建大厦",
        "parentId": null,
        "expand": false,
        "belongNum": 3,
        "level": 1,
        "checked": false,
        "property": null,
        "children": [{
            "id": "DLDM000008",
            "title": "城建大厦",
            "parentId": "GLC0000004",
            "expand": false,
            "belongNum": 0,
            "level": 2,
            "checked": false,
            "property": null,
            "children": [],
            "nodeKey": 24
        },
            {
                "id": "DLDM000187",
                "title": "上海市人民政府驻新疆办事处",
                "parentId": "GLC0000004",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 25
            },
            {
                "id": "DLDM000226",
                "title": "乌鲁木齐市地方税务局稽查局",
                "parentId": "GLC0000004",
                "expand": false,
                "belongNum": 0,
                "level": 2,
                "checked": false,
                "property": null,
                "children": [],
                "nodeKey": 26
            }
        ],
        "nodeKey": 23
    },
]


